"""media files mirrored from cdn

Revision ID: 133386ddbf4e
Revises: 7f252b2c7b3d
Create Date: 2026-09-08 06:00:34.302863
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '133386ddbf4e'
down_revision: Union[str, None] = '7f252b2c7b3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_files',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('kind', sa.Enum('photo', 'resume_file', name='media_kind'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('rel_path', sa.Text(), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('status', sa.Enum('pending', 'done', 'failed', 'gone', name='media_status'), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('discovered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('downloaded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'kind', name='uq_media_profile_kind')
    )
    op.create_index(op.f('ix_media_files_profile_id'), 'media_files', ['profile_id'], unique=False)
    op.create_index('ix_media_status', 'media_files', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_status', table_name='media_files')
    op.drop_index(op.f('ix_media_files_profile_id'), table_name='media_files')
    op.drop_table('media_files')
    # ### end Alembic commands ###
