"""candidate status reference

Revision ID: 5c76b5c6e217
Revises: a1b2c3d4e5f6
Create Date: 2026-09-11 11:04:33.467724
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '5c76b5c6e217'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_statuses',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('group_code', sa.String(length=32), nullable=True),
    sa.Column('group_title', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('background_color', sa.String(length=16), nullable=True),
    sa.Column('text_color', sa.String(length=16), nullable=True),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('legal_time_limit', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_candidate_statuses_sort', 'candidate_statuses', ['sort_order'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candidate_statuses_sort', table_name='candidate_statuses')
    op.drop_table('candidate_statuses')
    # ### end Alembic commands ###
