"""initial schema

Revision ID: 7af87976acca
Revises: 
Create Date: 2026-09-07 04:21:00.020847
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '7af87976acca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('admin', 'operator', 'viewer', name='admin_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_epoch', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('ats_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_enc', sa.Text(), nullable=False),
    sa.Column('proxy_enc', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('requests_ok', sa.BigInteger(), nullable=False),
    sa.Column('requests_failed', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('ats_users',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('role', sa.String(length=64), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidates',
    sa.Column('candidate_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('vacancy_id', sa.BigInteger(), nullable=True),
    sa.Column('vacancy_title', sa.Text(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('status_title', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recruiters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('managers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activity_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_index('ix_candidates_activity_synced', 'candidates', ['activity_synced_at'], unique=False)
    op.create_index('ix_candidates_created', 'candidates', ['created_at'], unique=False)
    op.create_index(op.f('ix_candidates_profile_id'), 'candidates', ['profile_id'], unique=False)
    op.create_index('ix_candidates_status_title', 'candidates', ['status_title'], unique=False)
    op.create_index(op.f('ix_candidates_vacancy_id'), 'candidates', ['vacancy_id'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('user_full_name', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_candidate_id'), 'comments', ['candidate_id'], unique=False)
    op.create_index('ix_comments_created', 'comments', ['created_at'], unique=False)
    op.create_table('contacts',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('profile_id', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('is_main', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_candidate_id'), 'contacts', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_contacts_profile_id'), 'contacts', ['profile_id'], unique=False)
    op.create_index('ix_contacts_type', 'contacts', ['type'], unique=False)
    op.create_table('export_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='export_status'), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('filename', sa.Text(), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('row_count', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('logs',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('candidate_id', sa.BigInteger(), nullable=True),
    sa.Column('date_time_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('user_full_name', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_logs_candidate_id'), 'logs', ['candidate_id'], unique=False)
    op.create_index('ix_logs_dt', 'logs', ['date_time_at'], unique=False)
    op.create_table('meta',
    sa.Column('k', sa.String(length=128), nullable=False),
    sa.Column('v', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('k')
    )
    op.create_table('profiles',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('first_name', sa.Text(), nullable=True),
    sa.Column('last_name', sa.Text(), nullable=True),
    sa.Column('middle_name', sa.Text(), nullable=True),
    sa.Column('phone', sa.Text(), nullable=True),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('cur_position', sa.Text(), nullable=True),
    sa.Column('cur_company', sa.Text(), nullable=True),
    sa.Column('experience', sa.Text(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('details_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_profiles_city', 'profiles', ['city'], unique=False)
    op.create_index('ix_profiles_details_synced', 'profiles', ['details_synced_at'], unique=False)
    op.create_index('ix_profiles_last_name', 'profiles', ['last_name'], unique=False)
    op.create_table('sync_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('sweep', 'details', 'activity', 'full', 'rolling', name='sync_kind'), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', 'cancelled', name='sync_status'), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('queued_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total', sa.BigInteger(), nullable=False),
    sa.Column('processed', sa.BigInteger(), nullable=False),
    sa.Column('created', sa.BigInteger(), nullable=False),
    sa.Column('updated', sa.BigInteger(), nullable=False),
    sa.Column('deferred', sa.BigInteger(), nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sync_runs_status', 'sync_runs', ['status', 'queued_at'], unique=False)
    op.create_table('vacancies',
    sa.Column('id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('persons_count', sa.Integer(), nullable=True),
    sa.Column('desired_closing_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_vacancies_status', 'vacancies', ['status'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['admin_users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_created', 'audit_log', ['created_at'], unique=False)
    op.create_table('resumes',
    sa.Column('profile_id', sa.BigInteger(), autoincrement=False, nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('source', sa.String(length=64), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('profile_id')
    )
    op.create_index('ix_resumes_source', 'resumes', ['source'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_resumes_source', table_name='resumes')
    op.drop_table('resumes')
    op.drop_index('ix_audit_created', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('ix_vacancies_status', table_name='vacancies')
    op.drop_table('vacancies')
    op.drop_index('ix_sync_runs_status', table_name='sync_runs')
    op.drop_table('sync_runs')
    op.drop_index('ix_profiles_last_name', table_name='profiles')
    op.drop_index('ix_profiles_details_synced', table_name='profiles')
    op.drop_index('ix_profiles_city', table_name='profiles')
    op.drop_table('profiles')
    op.drop_table('meta')
    op.drop_index('ix_logs_dt', table_name='logs')
    op.drop_index(op.f('ix_logs_candidate_id'), table_name='logs')
    op.drop_table('logs')
    op.drop_table('export_jobs')
    op.drop_index('ix_contacts_type', table_name='contacts')
    op.drop_index(op.f('ix_contacts_profile_id'), table_name='contacts')
    op.drop_index(op.f('ix_contacts_candidate_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index('ix_comments_created', table_name='comments')
    op.drop_index(op.f('ix_comments_candidate_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_candidates_vacancy_id'), table_name='candidates')
    op.drop_index('ix_candidates_status_title', table_name='candidates')
    op.drop_index(op.f('ix_candidates_profile_id'), table_name='candidates')
    op.drop_index('ix_candidates_created', table_name='candidates')
    op.drop_index('ix_candidates_activity_synced', table_name='candidates')
    op.drop_table('candidates')
    op.drop_table('ats_users')
    op.drop_table('ats_accounts')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    # ### end Alembic commands ###
