"""work history parsed from resumes

Revision ID: 7f252b2c7b3d
Revises: 7af87976acca
Create Date: 2026-09-07 11:48:11.336929
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7f252b2c7b3d'
down_revision: Union[str, None] = '7af87976acca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('profile_id', sa.BigInteger(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('company', sa.Text(), nullable=True),
    sa.Column('position', sa.Text(), nullable=True),
    sa.Column('started_at', sa.Date(), nullable=True),
    sa.Column('finished_at', sa.Date(), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('duration_text', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'ord', name='uq_work_history_profile_ord')
    )
    op.create_index('ix_work_history_company', 'work_history', ['company'], unique=False)
    op.create_index(op.f('ix_work_history_profile_id'), 'work_history', ['profile_id'], unique=False)
    op.create_index('ix_work_history_started', 'work_history', ['started_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_history_started', table_name='work_history')
    op.drop_index(op.f('ix_work_history_profile_id'), table_name='work_history')
    op.drop_index('ix_work_history_company', table_name='work_history')
    op.drop_table('work_history')
    # ### end Alembic commands ###
